### ISSUE TITLE
Kick idle users from broadcast rooms

### ISSUE THREAD

**Issue by ulope** [raiden-network/raiden-service-bundle#82]
# Problem Description

Currently users indefinitely accumulate in the discovery / broadcast rooms.
This has a negative impact on both server and client performance.

We should [kick](https://matrix.org/docs/spec/client_server/r0.6.0#post-matrix-client-r0-rooms-roomid-kick) users that [have been inactive](https://github.com/matrix-org/synapse/blob/master/docs/admin_api/user_admin_api.rst#query-account) for a while (e.g. 1 week) from the rooms.
If they come back online they will automatically re-join.

This could be implemented in the purger script.

## Open questions

- Can server admins kick users from the broadcast rooms, or room admins
  - If server admins are allowed to, how should the work be distributed? 
    - Easy option: Each server only kicks users that are registered via itself.
      - Downside: If a server gets removed from the federation those users will remain indefinitely
    - Only a specific server (e.g. the "first" one, as implemented for the room creation) kicks users
  - If not then only the user that was used to create the rooms (on the "first" server) can do anything anyway.

**Comment by fredo** [comment]
Currently I stuck at the last step to Kick the Users out of the broadcast rooms. Unfortunately, the broadcast rooms have been created by a User derived from an ETH address from which we dont have the key anymore. 

By default, only the room creator can kick users and also empower other users to have the right to kick. Ideally, the room creator should have been the server admin user. 

Now, we are stuck at a dilemma that we neither can kick any users from the room nor can the users leave the room since we do not have those keys either. 

This leaves two options: 

### Option 1 - SQL accrobatics

Im currently spending some time an try to change the power levels of users directly in the database of synapse in order to empower the server admin user. This is a slow and ongoing process (and a little bit frustrating)

### Option 2 - Forget the room 

We also could simply create a new room and pin the alias of the room as the global broadcast room. New Accounts automatically join this room.


### Pros and Cons
Option 1 seems to be the cleaner solutions since we can kick the users and the server can handle the cleanup process as intended. Furthermore, with 20000 users the Purger script has a proper "live" test environment and there are a lot of users to be kicked. 
On the other hand, it is somewhat time consuming to figure out how the database is build up (few to no documentation) and it could be a dead road which means it might not be possible to change the creator of the room. 

Option 2 is basically the opposite. It leaves the dirt of a room with 20000 users in the database but is a very quick solution (simply creating a new room). Furthermore, It will take a week (we could change the interval though) to see if the purger is working properly on the servers.

**Comment by hackaugusto** [comment]
> Currently users indefinitely accumulate in the discovery / broadcast rooms.
> This has a negative impact on both server and client performance.

To add to this, on the sync we receive

1. messages from the rooms the user is a member
2. join events from the other users in the same rooms
3. global presence information for the users which there is a shared room

1 and 2 can be filtered, since the updates are per room. this has been implemented in the Raiden client, so at the moment the client will not fetch broadcast messages (which are intended for the services and not other raiden nodes), and the node won't receive join events for the broadcast rooms (join information is not useful for any of the nodes).

3 it the problematic bit, since it is global information we can't easily filter it, because the presence data of every node is mixed together. This is a problem because our testing infrastructure creates dozens of users for each run, which quickly become a couple of thousand of users, which lead to a high load in the server to maintain the presence information, and a high payload size for the first sync. The work around, to alleviate the problem, is to quick inactive users from the broadcast rooms, this will remove the inactive users which should be the biggest bulk of users.

**Comment by Dominik1999** [comment]
> quick

quick or kick? If quick, wtf?
